version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dbmyscrapybook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123
    volumes:
      - .:/usr/src/app
    command: python app.py

volumes:
  db-data:
